# Generated by Django 2.2.4 on 2019-09-09 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='BoardVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ControlBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Nickname')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[model.models.check_mac_address], verbose_name='MAC address')),
                ('prototype_side', models.IntegerField(choices=[(0, 'Modelo Intensivo'), (1, 'Modelo Extensivo')], verbose_name='Prototype side')),
                ('board_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.BoardModel', verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=10, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('sensor_role', models.IntegerField(choices=[(0, 'Detecção de chuva na superfície'), (1, 'Detecção de chuva no ralo'), (2, 'Absorção de chuva'), (3, 'Quantidade de chuva')], verbose_name='Sensor role')),
                ('sensor_reading_conversion', models.FloatField(default=0.0, verbose_name='Sensor reading conversion')),
                ('control_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.ControlBoard', verbose_name='Control board')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50, verbose_name='Type')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('data_sheet', models.TextField(verbose_name='Data sheet')),
                ('precision', models.IntegerField(default=0, verbose_name='Decimal precision')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReadEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value_read', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Sensor', verbose_name='Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.SensorType', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_errors', models.BooleanField(default=False, verbose_name='Send errors notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlBoardEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status_received', models.CharField(max_length=10)),
                ('control_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.ControlBoard', verbose_name='ControlBoard')),
            ],
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='board_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.BoardVendor', verbose_name='Vendor'),
        ),
    ]
