# Generated by Django 2.2.5 on 2019-09-19 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20190916_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='board_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.BoardVendor', verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='boardvendor',
            name='description',
            field=models.CharField(max_length=100, unique=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='controlboard',
            name='board_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.BoardModel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='controlboard',
            name='nickname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='controlboard',
            name='prototype_side',
            field=models.IntegerField(choices=[(0, 'Modelo Intensivo'), (1, 'Modelo Extensivo')], verbose_name='Lado do modelo'),
        ),
        migrations.AlterField(
            model_name='controlboardevent',
            name='control_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.ControlBoard', verbose_name='Placa Controladora'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='control_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.ControlBoard', verbose_name='Placa Controladora'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_reading_conversion',
            field=models.FloatField(default=0.0, verbose_name='Conversão'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_role',
            field=models.IntegerField(choices=[(0, 'Detecção de chuva na superfície'), (1, 'Detecção de chuva no ralo'), (2, 'Absorção de chuva'), (3, 'Quantidade de chuva')], verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.SensorType', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='precision',
            field=models.IntegerField(default=0, verbose_name='Precisão'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='sensor_type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
    ]
