# Generated by Django 2.2.5 on 2019-09-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20190918_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreadevent',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='sensorreadevent',
            name='value_read',
            field=models.FloatField(verbose_name='Valor lido'),
        ),
    ]
