# Generated by Django 3.0.3 on 2020-02-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20190919_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
