# Generated by Django 3.0.3 on 2020-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_sensor_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlboard',
            name='prototype_area',
            field=models.FloatField(default=0.0, verbose_name='Área do modelo'),
        ),
    ]
