# Generated by Django 3.0.3 on 2020-02-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_controlboard_prototype_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorCalibrationInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de água')),
                ('interval_floor_value', models.IntegerField(verbose_name='Valor piso do intervalo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Sensor', verbose_name='Sensor')),
            ],
        ),
        migrations.AlterField(
            model_name='controlboard',
            name='prototype_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Área do modelo'),
        ),
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
