# Generated by Django 3.0.3 on 2020-02-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_auto_20200229_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcalibrationinterval',
            name='sensor',
            field=models.ForeignKey(limit_choices_to={'sensor_role': 2}, on_delete=django.db.models.deletion.CASCADE, to='model.Sensor', verbose_name='Sensor'),
        ),
    ]
