# Generated by Django 3.0.3 on 2020-02-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_auto_20200229_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_role',
            field=models.IntegerField(choices=[(0, 'Detecção de chuva na superfície'), (1, 'Detecção de chuva no ralo'), (2, 'Absorção de chuva'), (3, 'Quantidade de chuva'), (4, 'Temperatura do modelo')], verbose_name='Função'),
        ),
    ]
