# Generated by Django 3.0.3 on 2020-02-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20200229_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlboard',
            name='prototype_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Peso do modelo'),
        ),
    ]
